{% set name = "pytorchcv" %}
{% set version = "0.0.73" %}
{% set python-min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytorchcv-{{ version }}.tar.gz
  sha256: dff0a24dd982910034ce0c1eaafd2277f70c292c3a2bff9e5b90f09f38921186

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - requests
    - numpy
    - py-opencv
    - scipy
    - pytorch
    - torchvision

test:
  imports:
    - pytorchcv
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/osmr/imgclsmob
  summary: Image classification and segmentation models for PyTorch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
