{% set name = "pytorchcv" %}
{% set version = "0.0.70" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytorchcv-{{ version }}.tar.gz
  sha256: c63c82a4ce1f111c212aa66208c480531ad12f004a9d1737525985af849b35f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests
    - numpy
    - py-opencv
    - scipy
    - pytorch
    - torchvision

test:
  imports:
    - pytorchcv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/osmr/imgclsmob
  summary: Image classification and segmentation models for PyTorch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
