{% set name = "pytorchcv" %}
{% set version = "0.0.68" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytorchcv-{{ version }}.tar.gz
  sha256: 1798e555bd9572945c42e89f5df49dd85c0fae21f355261547e730f90ba319ae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests
    - numpy
    - py-opencv
    - scipy
    - pytorch
    - torchvision

test:
  imports:
    - pytorchcv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/osmr/imgclsmob
  summary: Image classification and segmentation models for PyTorch
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Tobias-Fischer
