{% set name = "pytorchcv" %}
{% set version = "0.0.69" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytorchcv-{{ version }}.tar.gz
  sha256: bfd491d89d8a6c06e1892f3618a825cace5a07e0f1d9c93b9cec34cb7cd2f23d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests
    - numpy
    - py-opencv
    - scipy
    - pytorch
    - torchvision

test:
  imports:
    - pytorchcv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/osmr/imgclsmob
  summary: Image classification and segmentation models for PyTorch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
